// Read the csv file
Table table;

void setup() {
  // You need to copy the csv file to the data directory.
  table = loadTable("meteorites.csv", "header");

  int totalItems = table.getRowCount();
  //println("--> Total Rows: " + totalItems);

  // Loop the csv file
  for (int i=0; i<totalItems; i++) {
    String recclass = table.getString(i, "recclass");
    println("["+i+"] recclass = " + recclass);
  }



  // The file writer
  PrintWriter output;
  // Create a new file in the sketch directory
  output = createWriter("classification.txt"); 
  println("--> Create File Ready");

  // Write data to the file
  output.println("# THIS FILE IS GENERATED BY THE \"CreateClassificationScript\" PROCESSING APP");
  output.println("");
  
  output.println("classification =");
  // Testing the writeObjectItem
  writeObjectItem(output, "the_name", "THE NAME", "THE DESCRIPTION", "THE CLASS", 31415, "THE ");
  output.println("");
  
  // create a small helper script for debugging....
  output.println("# Loop the classification object");
  output.println("# Used for debugging stuff...");
  output.println("# for i of classification");
  output.println("#   o = classification[i]");
  output.println("#   console.log 'name: ' + o.name");
  output.println("#   console.log 'desc: ' + o.desc");
  output.println("");

  // Writes the remaining data to the file
  output.flush();
  // Finishes the file
  output.close();
  println("--> File Writer Ready");
  
  // Stops the program
  exit();
}
